### ISSUE TITLE
[BUG] <Function 'tofts' Not Found in osipi Package Despite Being Listed in __init__.py>

### ISSUE THREAD

**Issue by MohamedNasser8** [OSIPI/pypi#26]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug
I am attempting to use the `tofts` function from the `osipi` package, which is listed as an importable function in the `__init__.py` file of the package. However, when I try to import `tofts`, I encounter an error indicating that the function is not found.

### Screenshots [optional]

Installed package init 
![image](https://github.com/OSIPI/pypi/assets/66921605/5c740b42-b6fa-46c1-a5d3-26104efa8f53)

### Steps To Reproduce

1. Install the `osipi` package in a virtual environment.
2. Attempt to import the `tofts` function using the following code:
   ```python
   from osipi import tofts


### Expected behavior

Error: AttributeError: module 'osipi' has no attribute 'tofts'

### Additional context

_No response_

### Are you working on this?

No

**Comment by AdarshRawat1** [comment]
The reason for the bug that you are facing is that

The [osipi 0.1.2 installed via pip ](https://pypi.org/project/osipi/0.1.2/)was last updated on Aug 16, 202. Whereas, `tofts` was added in  [this commit ](https://github.com/OSIPI/pypi/commit/8ac1b694732f6f79dc7b5f9399d9d64915e8b342#diff-8e0fee4bfe7a6e48190241b8fc0438dcf1028de5607f20e0fc522199110d6ac7) on  Sep 6, 2023 .

**Comment by MohamedNasser8** [comment]
Thanks Adarsh, I think the problem that there is example of the function usage in the [https://osipi.github.io/pypi/generated/api/osipi.tofts.html(documentation)
So it's example that the user will try.

As you said it depend on when they will update the package.

**Comment by AdarshRawat1** [comment]
> the problem example of the function usage in the [documentation](https://osipi.github.io/pypi/generated/api/osipi.tofts.html)  So it's an example that the user will try first.

I totally agree!

But the documentation is actually a work in progress, being developed based on the current repository structure and mostly contain temporary placeholders.
 
> As you said, it depends on when they will update the package.

Maintainers might update pip package once everything is updated and documented.
